name: Sign Windows package
description: Sign Windows executable using Azure Trusted Signing
inputs:
  azure_tenant_id:
    description: 'Azure AD tenant ID'
    required: true
  azure_client_id:
    description: 'Azure AD application (client) ID'
    required: true
  azure_client_secret:
    description: 'Azure AD client secret'
    required: true
  signing_endpoint:
    description: 'Azure Trusted Signing endpoint URL'
    required: true
  code_signing_account_name:
    description: 'Azure Trusted Signing account name'
    required: true
  certificate_profile_name:
    description: 'Certificate profile name'
    required: true
  binary_path:
    description: 'Path to the Windows binary to sign'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup and export all needed vars
      shell: pwsh
      run: |
        $BinaryPath = "${{ inputs.binary_path }}"

        if (-not (Test-Path $BinaryPath)) {
          Write-Error "Binary not found at: $BinaryPath"
          exit 1
        }

        Write-Host "Binary to sign: $BinaryPath"
        echo "BINARY_PATH=$BinaryPath" >> $env:GITHUB_ENV

    - name: Sign Windows Executable
      uses: azure/trusted-signing-action@v0.5.0
      with:
        azure-tenant-id: ${{ inputs.azure_tenant_id }}
        azure-client-id: ${{ inputs.azure_client_id }}
        azure-client-secret: ${{ inputs.azure_client_secret }}
        endpoint: ${{ inputs.signing_endpoint }}
        trusted-signing-account-name: ${{ inputs.code_signing_account_name }}
        certificate-profile-name: ${{ inputs.certificate_profile_name }}
        files: ${{ inputs.binary_path }}
        file-digest: SHA256
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256

    - name: Verify Signature
      shell: pwsh
      run: |
        $BinaryPath = "${{ inputs.binary_path }}"

        Write-Host "Verifying signature for: $BinaryPath"
        $sig = Get-AuthenticodeSignature -FilePath $BinaryPath

        Write-Host "  Status: $($sig.Status)"
        Write-Host "  Status Message: $($sig.StatusMessage)"

        if ($sig.SignerCertificate) {
          Write-Host "  Signer: $($sig.SignerCertificate.Subject)"
          Write-Host "  Issuer: $($sig.SignerCertificate.Issuer)"
          Write-Host "  Thumbprint: $($sig.SignerCertificate.Thumbprint)"
        }

        if ($sig.TimeStamperCertificate) {
          Write-Host "  Timestamped: Yes"
          Write-Host "  Timestamp Authority: $($sig.TimeStamperCertificate.Subject)"
        }

        if ($sig.Status -ne "Valid") {
          Write-Error "Signature verification failed for $BinaryPath"
          Write-Error "Status: $($sig.Status)"
          Write-Error "Message: $($sig.StatusMessage)"
          exit 1
        }

        Write-Host "Signature verified successfully!"
