#ifndef MD_STUB
#define MD_STUB
typedef enum { MNG_MIC_QUERY=95, MNG_MIC_CAPS=96, MNG_MIC_START=97, MNG_MIC_STOP=98, MNG_MIC_DATA=99, MNG_MIC_CONSENT=100, MNG_MIC_CONSENT_NEEDED=101, MNG_MIC_CONSENT_CANCEL=102 } RemoteManagementCommands;
#endif
